### ISSUE TITLE
[asking for help] sending parameter changes doesn't work in REAPER

### ISSUE THREAD

**Issue by nofishonfriday** [free-audio/clap-juce-extensions#101]
[REAPER](https://www.reaper.fm/) has recently introduced CLAP hosting support in its pre-release versions.
I've done a (quite basic) [CLAP plugin](https://github.com/nofishonfriday/Lauridsen-Schodder-Stereo-plugin) using JUCE + the clap-juce-extension.
It works fine in Bitwig but not in current REAPER's pre-release ('+dev') version.
Justin (REAPER dev) has confirmed and suggested that I may ask for help here to maybe troubleshoot it.

Link to the thread in the Cockos forum were the conservation started:
https://forum.cockos.com/showthread.php?p=2584377#post2584377

Thank you!

**Comment by baconpaul** [comment]
Ok I’ll take a peek! The param just doesn’t get updated is the prblem?

**Comment by nofishonfriday** [comment]
Hey, thanks a lot, appreciated.

The problem is that using my plugin (which uses the generic host GUI) in REAPER, moving the sliders has has absolutely no effect on the sound (the plugin's internal/DSP params aren't updated).
Justin says (quoted from the linked thread above):
> sending parameter changes to your plug-in doesn't seem to work
> the plug-in is receiving the CLAP_EVENT_PARAM_VALUE messages and processing it but then it gets lost in the class hierarchy abyss of JUCE

Tbh my hunch is that is an issue on REAPER's side (since it works fine in Bitwig), but Justin seems to have have difficulties troubleshooting it, so I'm looking for someone more knowledgeable in the inner working of JUCE/clap-juce-extension who can hopefully chime in.

**Comment by baconpaul** [comment]
Yeah if it works in bitwig then definitely 'something' is different. I just forked it and will take a quick look to see if anything obvious comes up. Thanks for flagging it!

**Comment by baconpaul** [comment]
Yeah I found the bug and its a reaper bug I think, having to do with you not having a GUI.

I'll write it up in the forum.

**Comment by baconpaul** [comment]
https://forum.cockos.com/showpost.php?p=2584761&postcount=42

there you go. Reaper is missing a CLAP api call which we depend on.
