### ISSUE TITLE
Error with contextMenuPopulate 

### ISSUE THREAD

**Issue by VASTDynamics** [free-audio/clap-juce-extensions#140]
Hi, I am trying to build a CLAP plugin for Vaporizer2 (https://github.com/VASTDynamics/Vaporizer2).
During CMake build I get several errors e.g: 

```
C:\Vaporizer2\clap-juce-extensions\src\wrapper\clap-juce-wrapper.cpp(176,1): error C2660: "clap::helpers::HostProxy<clap::helpers::M
isbehaviourHandler::Ignore,clap::helpers::CheckingLevel::Minimal>::contextMenuPopulate": Funktion akzeptiert keine 3 Argumente 

```
meaning "function does not accept 3 arguments ...."

I am using clap, clap-helpers and clap-juce-extensions from main.

But they donot seem to work together, or am I doing something wrong?

```
clap-juce-extensions/src/wrapper/clap-juce-wrapper.cpp from main

    juce::PopupMenu getEquivalentPopupMenu() const override
    {
        host.contextMenuPopulate(host.host(), &menuTarget, builder.builder());
```
-> 3 arguments
		
```
clap-helpers/include/clap/helpers/host-proxy.hh from main
		
bool contextMenuPopulate(const clap_context_menu_target_t *target, const clap_context_menu_builder_t *builder) const noexcept;
```
-> 2 arguments

Any ideas?

**Comment by baconpaul** [comment]
Well it looks like there was a change to clap-helpers which wasn't tested with clap-juce-extensions.

@trinitou @abique when you merged https://github.com/free-audio/clap-helpers/commit/7933f59b6462a757f8d284bb121bda7712e5644f how did you test it? That's what caused the problem.

@VASTDynamics I'm very sorry for this. I think that merge didn't take the full impact of the API change into account properly.  If you use the git hashes pinned to the clap-juce-extension as sub-modules it will build (that's what our CI tests) but everything built at head is not currently consistent indeed. Those hashes at head of CJE are clap @ 41964fa and clap-helpers @ 41e1086

Tagging @jatinchowdhury18 too.

**Comment by abique** [comment]
The clap-helpers don't have unit test on their own.
Usually when I change them, it is in the context of working on the clap-host or clap-plugins.
I'll check the code.

**Comment by abique** [comment]
Look at the error, it is because we removed the first argument which was the host.
This change is correct, the host proxy already had the pointer to the host, so it shouldn't take it again.

**Comment by baconpaul** [comment]
yeah i know that. The error is clear.

But just changing an api without a version tag, a deprecation of the old api, or anything other than a git hash is what bummed me out. 

I guess "does clap helpers present a stable versioned api or not" is really the problem.

**Comment by Trinitou** [comment]
The question is: what do we want?
I mean ATM clap-helpers has no version numbers and does not state to be a stable api. So when "submoduling" it like clap-juce-extension does, for me the hashes are the only way to ensure/assume compatibility and it's fine like this. But that's only my perspective and I'm not the most experienced here.
But maybe we should use versions for clap-helpers? If so, it become a bit confusing to track which clap version belongs to which separate clap-helpers version.

**Comment by baconpaul** [comment]
Right this is why we need locked versions with clap. I agree

**Comment by baconpaul** [comment]
(And apologies to @VASTDynamics for the github span. Let’s work this out on discord get a version lock message and update cje to use it)

**Comment by VASTDynamics** [comment]
Thank you. This is working now:

![image](https://github.com/free-audio/clap-juce-extensions/assets/35850267/4e75d0cc-888b-4769-b4df-60c0f668409b)
