### ISSUE TITLE
juce::AudioParameterChoice does not function

### ISSUE THREAD

**Issue by jorisroling** [free-audio/clap-juce-extensions#146]
Hi,

I successfully compiled my plugin with the clap-juce-extensions, and I use Bitwig (currently v5.1.7) to test it. All seems to work as expected, except parameters of type 'CHOICE' using juce::AudioParameterChoice. I was expecting it to allow for all (3 or more) options to be selectable using Bitwigs parameter list, but it seem to stuck with only the first and last options selectable.

I found that in the examples within clap-juce-extensions the NoteNamesPlugin also has a parameter exposed via juce::AudioParameterChoice, and after compiling it, it has the same effect. The list in the example is "Letters", "Do Re Mi", "Numbers", and via Bitwig only the first ("Letters") and the last option ("Numbers") is selectable. The knob jumps totally zero, to full without the intermediate options.

What strikes me is that numerical (float) parameters (working perfectly) show an orange ring around the parameter, when I move the parameter from with the CLAP plugin. Whereas the choice parameter does get a blue ring if I move the selected item to an intermediate one. Maybe that observation helps?

I don't know if this is a CLAP or clap-juce-extensions or Bitwig issue. But it would be lovely if this could be resolved. 

Cheers!

**Comment by jatinchowdhury18** [comment]
Hello!

I believe the issue you're seeing can be resolved with the [`CLAP_USE_JUCE_PARAMETER_RANGES`](https://github.com/free-audio/clap-juce-extensions/blob/8d0754f5d6ca1e95bc207b7743c04ebd7dc17e88/README.md?plain=1#L151) setting in CMake. For most of my plugins, I set `CLAP_USE_JUCE_PARAMETER_RANGES` to `DISCRETE`, which I think is what you'll want here. Here's [an example](https://github.com/Chowdhury-DSP/BYOD/blob/main/CMakeLists.txt#L118) of how I have the CMake parameters set up for one of my plugins.

I'm having trouble remembering why we decided to make that option `OFF` by default, but maybe Paul can jog my memory when he's back from vacation.

**Comment by jorisroling** [comment]
That did the trick. Thanks a million!
I will have a close look at all those setting.
