### ISSUE TITLE
no member named ‘nonParameterStateChanged’ when building

### ISSUE THREAD

**Issue by silverhikari** [free-audio/clap-juce-extensions#41]
when trying to build a plugin with clap-juce-\extensions the following error appears causing the build to fail

```
/home/silver/.cache/yay/monique-monosynth-git/src/monique-monosynth/libs/clap-juce-extensions/src/wrapper/clap-juce-wrapper.cpp: In member function ‘virtual void ClapJuceWrapper::audioProcessorChanged(juce::AudioProcessor*, const juce::AudioProcessorListener::ChangeDetails&)’:
/home/silver/.cache/yay/monique-monosynth-git/src/monique-monosynth/libs/clap-juce-extensions/src/wrapper/clap-juce-wrapper.cpp:231:21: error: ‘const struct juce::AudioProcessorListener::ChangeDetails’ has no member named ‘nonParameterStateChanged’; did you mean ‘parameterInfoChanged’?

```
juce version :6.1.6

**Comment by baconpaul** [comment]
Hi!

Let me take a look. Monique built for us without problem in CI.

Are you sure your submodules are up to date in monique? Things have been moving around.

Also what's your OS?

Thanks

**Comment by baconpaul** [comment]
(by the way the nonParameterStateChanged error would happen if either (1) you were accidentally using juce 6.1.1 or earlier; (2) your clap-juce-extensions were on the main branch and not on next; or (3) we have something else wrong :) )

**Comment by baconpaul** [comment]
And we've built monique cleanly at 5c81f90fa366279815303d4aaa38020b2b3c53a2 using the shipped JUCE and clap-juce-wrappers it comes with.

So a few more details would be lovely! Thanks.

**Comment by silverhikari** [comment]
the OS i am using is manjaro and i am building with the pkgbuild located here https://aur.archlinux.org/packages/monique-monosynth-git.i was mistaken as the version of juce checkout is 6.1.2 as it seems any latter version cause errors.

**Comment by silverhikari** [comment]
it seemed setting juce to pull from the development branch and clap-juce extensions to pull for the next branch seems to have fixed the issue

**Comment by baconpaul** [comment]
Yeah I moved next to main just now too
But Monique submodules at head should work
If they don’t I would love to know your fit hash at Monique juce and cje

**Comment by baconpaul** [comment]
And thanks of course for the report!
