### ISSUE TITLE
Unconditional paramsRescan() crash

### ISSUE THREAD

**Issue by tim-janik** [free-audio/clap-juce-extensions#46]
Surge XT Effects crashes if the host has not (yet) implemented clap_host_params:

Here, the call to paramsRescan() is unconditional:

https://github.com/free-audio/clap-juce-extensions/blob/dad123ef8a08e28e3b172bd5e9a45caa9c0be7a8/src/wrapper/clap-juce-wrapper.cpp#L274

**Comment by baconpaul** [comment]
Oh thank you, I will fix that this weekend. 

The plugin wrapper should avoid that crashing … wonder why it doesn’t

will investigate and report back

**Comment by baconpaul** [comment]
Yes I need to wrap that in a host,can use params if - will do and will update surge. 

Can you build a working version as a test in the interim? Don’t want to stall your development

**Comment by tim-janik** [comment]
> Yes I need to wrap that in a host,can use params if - will do and will update surge.
> 
> Can you build a working version as a test in the interim? Don’t want to stall your development

Don't worry, I just need to implement more interfaces in my host.
(And I cannot easily build Surge, JUCE and the cmake based clap examples on Ubuntu 20.04, so I'm working with CLAP binary-only plugins atm)

I'm planning for a summary at the end about things to consider when implementing a host, not sure where to put it though. Pitfalls I've run into so far:
- GUI support needs timer support
- GUI support needs on_main_thread() support
- Don't expect plugins to implement floating windows, so GUI also needs a host with X11Window embedding support
- Many plugins crash if clap.thread-check isn't provided - and paramsRescan ;-)
etc.

It'd be helpful for people to know these issues *before* attempting a port, so it should be somewhere easily accessible for developers.

**Comment by baconpaul** [comment]
Yes GUI support requires timer fd and on_main_thread on linux, practically. I should make the juce plugins return false for isGui on linux if the host doesn't support that.

I have a PR in for the host.Can before host.Do which jatin will review. The plugin is at fault in your fourth case.

**Comment by baconpaul** [comment]
oh and the host is at fault in the fifth. Indeed dont' call resize if can_resize is false. just like i shouldn't call paramRescan if canParams is false :)

**Comment by baconpaul** [comment]
> (And I cannot easily build Surge, JUCE and the cmake based clap examples on Ubuntu 20.04, so I'm working with CLAP binary-only plugins atm)

I use ubuntu 20.04 every day and it is what our CI pipeline use. The only thing I had to do on my desktop box (but our pipelines do this automatically) is grab a newer version of cmake from cmake.org

Just FYI

**Comment by baconpaul** [comment]
I'm sorry this auto-closed because i pushed a fix but you have other comments so reopening

**Comment by baconpaul** [comment]
Anyway i've kicked off a surge build with this defense in place. About 2 hours for a nightly all told tops.

**Comment by baconpaul** [comment]
I'm going to close this and consolidate a new issue about linux.
