### ISSUE TITLE
CMake interface target property issues

### ISSUE THREAD

**Issue by tobiashienzsch** [free-audio/clap-juce-extensions#53]
CMake fails to load because of properties being set, which are not whitelisted for interface targets.

```cmake
# Plugin project
add_subdirectory(3rd_party/JUCE)
add_subdirectory(3rd_party/clap-juce-extensions EXCLUDE_FROM_ALL) 
```

```sh
# Errors
INTERFACE_LIBRARY targets may only have whitelisted properties.  The property "POSITION_INDEPENDENT_CODE" is not allowed.
INTERFACE_LIBRARY targets may only have whitelisted properties.  The property "CXX_STANDARD" is not allowed.
```

Some quick googling suggests that CMake's behavior has changed across versions. [See here.](https://discourse.cmake.org/t/how-to-find-current-interface-library-property-whitelist/4784)

## Build System

- **OS**: Ubuntu 21.10 impish
- **Kernel**: x86_64 Linux 5.13.0-44-generic
- **CMake**: 3.18.4

### Part 1 

CMake doesn't accept source files in `add_library`, if the `INTERFACE` property is being used. Using `target_sources` fixes this issue.

Convert:

https://github.com/free-audio/clap-juce-extensions/blob/bc548cb6dbb4ca763e8c5ca7e4a45349275561a0/CMakeLists.txt#L44-L45

To:
```cmake
add_library(clap_juce_sources INTERFACE )
target_sources(clap_juce_sources INTERFACE ${CMAKE_CURRENT_SOURCE_DIR}/src/wrapper/clap-juce-wrapper.cpp)
# set_property(TARGET clap_juce_sources PROPERTY CXX_STANDARD ${CLAP_CXX_STANDARD})
```

### Part 2

I had to disable all places where non-whitelisted properties where bing used.

Convert:

https://github.com/free-audio/clap-juce-extensions/blob/bc548cb6dbb4ca763e8c5ca7e4a45349275561a0/cmake/ClapTargetHelpers.cmake#L26-L29

To:
```cmake
get_property(SRC TARGET clap_juce_sources PROPERTY INTERFACE_SOURCES)
add_library(${claptarget} MODULE ${SRC})
# get_property(CLAP_CXX_STANDARD TARGET clap_juce_sources PROPERTY CXX_STANDARD)
```

### Part 3

The `clap-helpers` project is also affected

Convert:

https://github.com/free-audio/clap-helpers/blob/2bb43c18788c689708ead6f127a2d75e772ab389/CMakeLists.txt#L7-L10

To:
```cmake
add_library(clap-helpers INTERFACE)
# set_target_properties(clap-helpers PROPERTIES
#     POSITION_INDEPENDENT_CODE ON
#     CXX_STANDARD 11)
```

**Comment by tobiashienzsch** [comment]
- Related issue to `CXX_STANDARD` property: [gitlab.kitware.com/cmake/cmake/-/issues/23189](https://gitlab.kitware.com/cmake/cmake/-/issues/23189)
- Possible solution for `POSITION_INDEPENDENT_CODE` property: Replace with `INTERFACE_POSITION_INDEPENDENT_CODE`. [See here](https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_POSITION_INDEPENDENT_CODE.html)

**Comment by baconpaul** [comment]
The solution here is to require cmake 3.21 or later, which is what we've been using for our builds. We need to update the version statement in the CMakeList to make this clear.

**Comment by baconpaul** [comment]
but thank you for the excellent report!

**Comment by tobiashienzsch** [comment]
I can confirm this. I have replaced the system CMake from Ubuntu with a version from Snap. Now it is 3.23.

A CI pipeline with a small demo plugin has also worked on other systems. Tested (all `C++20` with `juce7` branch):

|OS| Compiler|CMake |
|:----:|:----:|:----:|
|macOS Universal Binary (Monterey Intel Host)|Xcode (13.2.1) + Ninja| 3.21 |
|macOS AppleSilicon (Monterey M1 Host)|Xcode (13.0.0) + Ninja| 3.22.2 |
|windows-2019 (GitHub Virtual Env) |VS2019 + ClangCL | 3.23.2 |
|Ubuntu 21.10  |Gcc-11.2 + Ninja | 3.23.2 |
|Ubuntu 21.10  |Clang-14.0.5 + Ninja | 3.23.2 |
|Ubuntu 20.04 |Gcc-9.4 + Ninja | 3.23.2 |

Only compiling & linking has been tested, no CLAP binary was run. VST3 & AU from the same project (still) passed pluginval. Which was expected. :)

**Comment by baconpaul** [comment]
Great. You can use <https://github.com/surge-synthesizer/clap-info> to poke at your binary if you want without running a full blown host. (We are slowly moving that to JSON output so its half and half now).

**Comment by tobiashienzsch** [comment]
Awesome. `clap-info` worked. Plugin name, type & parameter reported as expected.
