### ISSUE TITLE
Build fails on JUCE v7 master branch

### ISSUE THREAD

**Issue by tobiashienzsch** [free-audio/clap-juce-extensions#60]
## Error
```sh
.../clap-juce-wrapper.cpp:321:10: error: ‘bool ClapJuceWrapper::getCurrentPosition(juce::AudioPlayHead::CurrentPositionInfo&)’ marked ‘override’, but does not override
  321 |     bool getCurrentPosition(juce::AudioPlayHead::CurrentPositionInfo &info) override
      |          ^~~~~~~~~~~~~~~~~~
```

## Solution

- Method has been marked deprecated and is not `virtual` anymore. Either remove the `override` or switch to the replacement `getPosition`. Reasoning is that not all hosts support the deprecated  method.

**Comment by baconpaul** [comment]
Yeah I saw that last night also. I’ll ifdef it now they have a stable juce version for 7. Thanks

**Comment by baconpaul** [comment]
@tobiashienzsch OK have a PR in and awaiting a review.

Do you use discord by the way? If so can you find me and i'll invite you to the clap dev discord for people working on plugins and the like.
