### ISSUE TITLE
A few CI features which would be awesome

### ISSUE THREAD

**Issue by baconpaul** [free-audio/clap-juce-extensions#73]
1: Can we run `clap-info` on the plugin which result and make sure it doesn't segv?
2: Can we also add a juce 6.0.7?

**Comment by jatinchowdhury18** [comment]
Oh yeah, these are good ideas! Are there any arguments you'd recommend for `clap-info`? Or just the default arguments are fine?

**Comment by baconpaul** [comment]
You could just point it at the built clap yeah and that’s fine!

**Comment by jatinchowdhury18** [comment]
Closed with #75

**Comment by baconpaul** [comment]
Amazing!
